Cefpython123
cztomczak/cefpython pull request #669
Opened 2024-05-12 07:42 UTC by linesight

Added cef 123 support for python 3.10 and 3.11 at windows
Some of the fix is coming from https://github.com/llcc01/cefpython

qt.py example added pyqt6 support
addressing https://github.com/cztomczak/cefpython/issues/652

2024-06-13 08:52 UTC, WoolenWang commented
when this can merge and publish one package? users are waiting

2024-06-13 08:53 UTC, WoolenWang commented
@cztomczak

2024-06-21 23:40 UTC, SoprachevAK commented
Thanks for the port to 123. I think that this repository is no longer supported. 
You did a great job and could post an unofficial release like [this](https://pypi.org/project/cefpython3-for-python-3.9.6-unofficial/)

Or may be wright small build instruction. I try build your fork with `prebuilt-cef` and `automate.py` script, but got errors. 
I use `visual studio 2022 community`, `python 3.7.7`.

I download and unpack to `build` folder `cef_binary_123.0.7+g6a21509+chromium-123.0.6312.46_windows64` by spotify (Standard Distribution)
Then run `python ..\tools\automate.py --prebuilt-cef`

And got this:
<details>
  <summary>Output</summary>
  
```
[automate.py] Build cef projects...
[automate.py] Create build_cefclient/ dir in cef_binary*/ dir
[automate.py] Build cefclient, cefsimple, ceftests
[automate.py] Running 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat amd64 && cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..' in 'C:\Users\Andrei\Desktop\newcef\cefpython\build\cef_binary_123.0.7+g6a21509+chromium-123.0.6312.46_windows64\build_cefclient'...
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.10.3
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
-- The C compiler identification is MSVC 19.40.33811.0
-- The CXX compiler identification is MSVC 19.40.33811.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features       
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info    
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at cmake/cef_variables.cmake:629 (message):
  ATL is not supported by your VC installation.
Call Stack (most recent call first):
  cmake/FindCEF.cmake:38 (include)
  CMakeLists.txt:210 (find_package)


-- *** CEF CONFIGURATION SETTINGS ***
-- Generator:                    Ninja
-- Platform:                     Windows
-- Project architecture:         x86_64
-- Build type:                   Release
-- Binary distribution root:     C:/Users/Andrei/Desktop/newcef/cefpython/build/cef_binary_123.0.7+g6a21509+chromium-123.0.6312.46_windows64
-- Visual Studio ATL support:    OFF
-- CEF sandbox:                  ON
-- Standard libraries:           comctl32.lib;gdi32.lib;rpcrt4.lib;shlwapi.lib;ws2_32.lib;Advapi32.lib;dbghelp.lib;Delayimp.lib;ntdll.lib;OleAut32.lib;PowrProf.lib;Propsys.lib;psapi.lib;SetupAPI.lib;Shell32.lib;Shcore.lib;Userenv.lib;version.lib;wbemuuid.lib;WindowsApp.lib;winmm.lib
-- Compile defines:              __STDC_CONSTANT_MACROS;__STDC_FORMAT_MACROS;WIN32;_WIN32;_WINDOWS;UNICODE;_UNICODE;WINVER=0x0A00;_WIN32_WINNT=0x0A00;NTDDI_VERSION=NTDDI_WIN10_FE;NOMINMAX;WIN32_LEAN_AND_MEAN;_HAS_EXCEPTIONS=0;PSAPI_VERSION=1;CEF_USE_SANDBOX
-- Compile defines (Debug):      _HAS_ITERATOR_DEBUGGING=0
-- Compile defines (Release):    NDEBUG;_NDEBUG
-- C compile flags:              /MP;/Gy;/GR-;/W4;/WX;/wd4100;/wd4127;/wd4244;/wd4324;/wd4481;/wd4512;/wd4701;/wd4702;/wd4996;/Zi
-- C compile flags (Debug):      /MTd;/RTC1;/Od
-- C compile flags (Release):    /MT;/O2;/Ob2;/GF
-- C++ compile flags:            /MP;/Gy;/GR-;/W4;/WX;/wd4100;/wd4127;/wd4244;/wd4324;/wd4481;/wd4512;/wd4701;/wd4702;/wd4996;/Zi /std:c++17
-- C++ compile flags (Debug):    /MTd;/RTC1;/Od
-- C++ compile flags (Release):  /MT;/O2;/Ob2;/GF
-- Exe link flags:                /MANIFEST:NO;/LARGEADDRESSAWARE;/DELAYLOAD:api-ms-win-core-winrt-error-l1-1-0.dll;/DELAYLOAD:api-ms-win-core-winrt-l1-1-0.dll;/DELAYLOAD:api-ms-win-core-winrt-string-l1-1-0.dll;/DELAYLOAD:advapi32.dll;/DELAYLOAD:comctl32.dll;/DELAYLOAD:comdlg32.dll;/DELAYLOAD:credui.dll;/DELAYLOAD:cryptui.dll;/DELAYLOAD:d3d11.dll;/DELAYLOAD:d3d9.dll;/DELAYLOAD:dwmapi.dll;/DELAYLOAD:dxgi.dll;/DELAYLOAD:dxva2.dll;/DELAYLOAD:esent.dll;/DELAYLOAD:gdi32.dll;/DELAYLOAD:hid.dll;/DELAYLOAD:imagehlp.dll;/DELAYLOAD:imm32.dll;/DELAYLOAD:msi.dll;/DELAYLOAD:netapi32.dll;/DELAYLOAD:ncrypt.dll;/DELAYLOAD:ole32.dll;/DELAYLOAD:oleacc.dll;/DELAYLOAD:propsys.dll;/DELAYLOAD:psapi.dll;/DELAYLOAD:rpcrt4.dll;/DELAYLOAD:rstrtmgr.dll;/DELAYLOAD:setupapi.dll;/DELAYLOAD:shell32.dll;/DELAYLOAD:shlwapi.dll;/DELAYLOAD:uiautomationcore.dll;/DELAYLOAD:urlmon.dll;/DELAYLOAD:user32.dll;/DELAYLOAD:usp10.dll;/DELAYLOAD:uxtheme.dll;/DELAYLOAD:wer.dll;/DELAYLOAD:wevtapi.dll;/DELAYLOAD:wininet.dll;/DELAYLOAD:winusb.dll;/DELAYLOAD:wsock32.dll;/DELAYLOAD:wtsapi32.dll;/STACK:0x800000
-- Exe link flags (Debug):       /DEBUG
-- Exe link flags (Release):
-- Shared link flags:
-- Shared link flags (Debug):    /DEBUG
-- Shared link flags (Release):
-- CEF Binary files:             chrome_elf.dll;d3dcompiler_47.dll;libcef.dll;libEGL.dll;libGLESv2.dll;snapshot_blob.bin;v8_context_snapshot.bin;vk_swiftshader.dll;vk_swiftshader_icd.json;vulkan-1.dll;dxil.dll;dxcompiler.dll
-- CEF Resource files:           chrome_100_percent.pak;chrome_200_percent.pak;resources.pak;icudtl.dat;locales
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
CMake Warning at CMakeLists.txt:254 (message):
  Doxygen must be installed to generate API documentation.


-- Configuring done (1.6s)
-- Generating done (0.3s)
-- Build files have been written to: C:/Users/Andrei/Desktop/newcef/cefpython/build/cef_binary_123.0.7+g6a21509+chromium-123.0.6312.46_windows64/build_cefclient
[automate.py] OK
[automate.py] Running 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat amd64 && ninja -j 8 cefclient cefsimple ceftests' in 'C:\Users\Andrei\Desktop\newcef\cefpython\build\cef_binary_123.0.7+g6a21509+chromium-123.0.6312.46_windows64\build_cefclient'...
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.10.3
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
[1/388] Building CXX object libcef_dll_wrapper\CMakeFiles\libcef_dll_wrapper.dir\base\cef_atomic_flag.cc.obj
FAILED: libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_atomic_flag.cc.obj 
C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1440~1.338\bin\Hostx64\x64\cl.exe  /nologo /TP -DCEF_USE_SANDBOX -DNDEBUG -DNOMINMAX -DNTDDI_VERSION=NTDDI_WIN10_FE -DPSAPI_VERSION=1 -DUNICODE -DWIN32 -DWIN32_LEAN_AND_MEAN -DWINVER=0x0A00 -DWRAPPING_CEF_SHARED -D_HAS_EXCEPTIONS=0 -D_NDEBUG -D_UNICODE -D_WIN32 -D_WIN32_WINNT=0x0A00 -D_WINDOWS 
-D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -IC:\Users\Andrei\Desktop\newcef\cefpython\build\cef_binary_123.0.7+g6a21509+chromium-123.0.6312.46_windows64 -MD /MP /Gy /GR- /W4 /WX /wd4100 /wd4127 /wd4244 /wd4324 /wd4481 /wd4512 /wd4701 /wd4702 /wd4996 /Zi /std:c++17 /MT /O2 /Ob2 /GF /showIncludes /Folibcef_dll_wrapper\CMakeFiles\libcef_dll_wrapper.dir\base\cef_atomic_flag.cc.obj /Fdlibcef_dll_wrapper\CMakeFiles\libcef_dll_wrapper.dir\libcef_dll_wrapper.pdb /FS -c C:\Users\Andrei\Desktop\newcef\cefpython\build\cef_binary_123.0.7+g6a21509+chromium-123.0.6312.46_windows64\libcef_dll\base\cef_atomic_flag.cc
cl : Command line warning D9025 : overriding '/MD' with '/MT'
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\fileapi.h(1105): error C2061: syntax error: identifier 'FILE_INFO_BY_HANDLE_CLASS'
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winbase.h(9118): error C2061: syntax error: identifier 'FILE_INFO_BY_HANDLE_CLASS'
[2/388] Building CXX object libcef_dll_wrapper\CMakeFiles\libcef_dll_wrapp [...]

2024-06-22 16:34 UTC, linesight commented
> Thanks for the port to 123. I think that this repository is no longer supported. You did a great job and could post an unofficial release like [this](https://pypi.org/project/cefpython3-for-python-3.9.6-unofficial/)
> 
> Or may be wright small build instruction. I try build your fork with `prebuilt-cef` and `automate.py` script, but got errors. I use `visual studio 2022 community`, `python 3.7.7`.
> 
> I download and unpack to `build` folder `cef_binary_123.0.7+g6a21509+chromium-123.0.6312.46_windows64` by spotify (Standard Distribution) Then run `python ..\tools\automate.py --prebuilt-cef`
> 
> And got this:
> 
> Output
> ```
> [automate.py] Build cef projects...
> [automate.py] Create build_cefclient/ dir in cef_binary*/ dir
> [automate.py] Build cefclient, cefsimple, ceftests
> [automate.py] Running 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat amd64 && cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..' in 'C:\Users\Andrei\Desktop\newcef\cefpython\build\cef_binary_123.0.7+g6a21509+chromium-123.0.6312.46_windows64\build_cefclient'...
> **********************************************************************
> ** Visual Studio 2022 Developer Command Prompt v17.10.3
> ** Copyright (c) 2022 Microsoft Corporation
> **********************************************************************
> [vcvarsall.bat] Environment initialized for: 'x64'
> -- The C compiler identification is MSVC 19.40.33811.0
> -- The CXX compiler identification is MSVC 19.40.33811.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - skipped
> -- Detecting C compile features       
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info    
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> CMake Warning at cmake/cef_variables.cmake:629 (message):
>   ATL is not supported by your VC installation.
> Call Stack (most recent call first):
>   cmake/FindCEF.cmake:38 (include)
>   CMakeLists.txt:210 (find_package)
> 
> 
> -- *** CEF CONFIGURATION SETTINGS ***
> -- Generator:                    Ninja
> -- Platform:                     Windows
> -- Project architecture:         x86_64
> -- Build type:                   Release
> -- Binary distribution root:     C:/Users/Andrei/Desktop/newcef/cefpython/build/cef_binary_123.0.7+g6a21509+chromium-123.0.6312.46_windows64
> -- Visual Studio ATL support:    OFF
> -- CEF sandbox:                  ON
> -- Standard libraries:           comctl32.lib;gdi32.lib;rpcrt4.lib;shlwapi.lib;ws2_32.lib;Advapi32.lib;dbghelp.lib;Delayimp.lib;ntdll.lib;OleAut32.lib;PowrProf.lib;Propsys.lib;psapi.lib;SetupAPI.lib;Shell32.lib;Shcore.lib;Userenv.lib;version.lib;wbemuuid.lib;WindowsApp.lib;winmm.lib
> -- Compile defines:              __STDC_CONSTANT_MACROS;__STDC_FORMAT_MACROS;WIN32;_WIN32;_WINDOWS;UNICODE;_UNICODE;WINVER=0x0A00;_WIN32_WINNT=0x0A00;NTDDI_VERSION=NTDDI_WIN10_FE;NOMINMAX;WIN32_LEAN_AND_MEAN;_HAS_EXCEPTIONS=0;PSAPI_VERSION=1;CEF_USE_SANDBOX
> -- Compile defines (Debug):      _HAS_ITERATOR_DEBUGGING=0
> -- Compile defines (Release):    NDEBUG;_NDEBUG
> -- C compile flags:              /MP;/Gy;/GR-;/W4;/WX;/wd4100;/wd4127;/wd4244;/wd4324;/wd4481;/wd4512;/wd4701;/wd4702;/wd4996;/Zi
> -- C compile flags (Debug):      /MTd;/RTC1;/Od
> -- C compile flags (Release):    /MT;/O2;/Ob2;/GF
> -- C++ compile flags:            /MP;/Gy;/GR-;/W4;/WX;/wd4100;/wd4127;/wd4244;/wd4324;/wd4481;/wd4512;/wd4701;/wd4702;/wd4996;/Zi /std:c++17
> -- C++ compile flags (Debug):    /MTd;/RTC1;/Od
> -- C++ compile flags (Release):  /MT;/O2;/Ob2;/GF
> -- Exe link flags:                /MANIFEST:NO;/LARGEADDRESSAWARE;/DELAYLOAD:api-ms-win-core-winrt-error-l1-1-0.dll;/DELAYLOAD:api-ms-win-core-winrt-l1-1-0.dll;/DELAYLOAD:api-ms-win-core-winrt-string-l1-1-0.dll;/DELAYLOAD:advapi32.dll;/DELAYLOAD:comctl32.dll;/DELAYLOAD:comdlg32.dll;/DELAYLOAD:credui.dll;/DELAYLOAD:cryptui.dll;/DELAYLOAD:d3d11.dll;/DELAYLOAD:d3d9.dll;/DELAYLOAD:dwmapi.dll;/DELAYLOAD:dxgi.dll;/DELAYLOAD:dxva2.dll;/DELAYLOAD:esent.dll;/DELAYLOAD:gdi32.dll;/DELAYLOAD:hid.dll;/DELAYLOAD:imagehlp.dll;/DELAYLOAD:imm32.dll;/DELAYLOAD:msi.dll;/DELAYLOAD:netapi32.dll;/DELAYLOAD:ncrypt.dll;/DELAYLOAD:ole32.dll;/DELAYLOAD:oleacc.dll;/DELAYLOAD:propsys.dll;/DELAYLOAD:psapi.dll;/DELAYLOAD:rpcrt4.dll;/DELAYLOAD:rstrtmgr.dll;/DELAYLOAD:setupapi.dll;/DELAYLOAD:shell32.dll;/DELAYLOAD:shlwapi.dll;/DELAYLOAD:uiautomationcore.dll;/DELAYLOAD:urlmon.dll;/DELAYLOAD:user32.dll;/DELAYLOAD:usp10.dll;/DELAYLOAD:uxtheme.dll;/DELAYLOAD:wer.dll;/DELAYLOAD:wevtapi.dll;/DELAYLOAD:wininet.dll;/DELAYLOAD:winusb.dll;/DELAYLOAD:wsock32.dll;/DELAYLOAD:wtsapi32.dll;/STACK:0x800000
> -- Exe link flags (Debug):       /DEBUG
> -- Exe link flags (Release):
> -- Shared link flags:
> -- Shared link flags (Debug):    /DEBUG
> -- Shared link flags (Release):
> -- CEF Binary files:             chrome_elf.dll;d3dcompiler_47.dll;libcef.dll;libEGL.dll;libGLESv2.dll;snapshot_blob.bin;v8_context_snapshot.bin;vk_swiftshader.dll;vk_swiftshader_icd.json;vulkan-1.dll;dxil.dll;dxcompiler.dll
> -- CEF Resource files:           chrome_100_percent.pak;chrome_200_percent.pak;resources.pak;icudtl.dat;locales
> -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
> CMake Warning at CMakeLists.txt:254 (message):
>   Doxygen must be installed to generate API documentation.
> 
> 
> -- Configuring done (1.6s)
> -- Generating done (0.3s)
> -- Build files have been written to: C:/Users/Andrei/Desktop/newcef/cefpython/build/cef_binary_123.0.7+g6a21509+chromium-123.0.6312.46_windows64/build_cefclient
> [automate.py] OK
> [automate.py] Running 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat amd64 && ninja -j 8 cefclient cefsimple ceftests' in 'C:\Users\Andrei\Desktop\newcef\cefpython\build\cef_binary_123.0.7+g6a21509+chromium-123.0.6312.46_windows64\build_cefclient'...
> **********************************************************************
> ** Visual Studio 2022 Developer Command Prompt v17.10.3
> ** Copyright (c) 2022 Microsoft Corporation
> **********************************************************************
> [vcvarsall.bat] Environment initialized for: 'x64'
> [1/388] Building CXX object libcef_dll_wrapper\CMakeFiles\libcef_dll_wrapper.dir\base\cef_atomic_flag.cc.obj
> FAILED: libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_atomic_flag.cc.obj 
> C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1440~1.338\bin\Hostx64\x64\cl.exe  /nologo /TP -DCEF_USE_SANDBOX -DNDEBUG -DNOMINMAX -DNTDDI_VERSION=NTDDI_WIN10_FE -DPSAPI_VERSION=1 -DUNICODE -DWIN32 -DWIN32_LEAN_AND_MEAN -DWINVER=0x0A00 -DWRAPPING_CEF_SHARED -D_HAS_EXCEPTIONS=0 -D_NDEBUG -D_UNICODE -D_WIN32 -D_WIN32_WINNT=0x0A00 -D_WINDOWS 
> -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -IC:\Users\Andrei\Desktop\newcef\cefpython\build\cef_binary_123.0.7+g6a21509+chromium-123.0.6312.46_windows64 -MD /MP /Gy /GR- /W4 /WX /wd4100 /wd4127 /wd4244 /wd4324 /wd4481 /wd4512 /wd4701 /wd4702 /wd4996 /Zi /std:c++17 /MT /O2 /Ob2 /GF /showIncludes /Folibcef_dll_wrapper\CMakeFiles\libcef_dll_wrapper.dir\base\cef_atomic_flag.cc.obj /Fdlibcef_dll_wrapper\CMakeFiles\libcef_dll_wrapper.dir\libcef_dll_wrapper.pdb /FS -c C:\Users\Andrei\Desktop\newcef\cefpython\build\cef_binary_123.0.7+g6a21509+chromium-123.0.6312.46_windows64\libcef_dll\base\cef_atomic_flag.cc
> cl : Command line warning D9025 : overriding '/MD' with '/MT'
> C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\fileapi.h(1105): error C2061: syntax error: identifier 'FILE_INFO_BY_HANDLE_CLASS'
> C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winbase.h(9118): err [...]

2024-06-22 20:03 UTC, SoprachevAK commented
> As a reference, my machine has 10.0.22621.0 sdk version.

Thank you! This version helped me. With this lib compiled and works.

2025-02-07 20:50 UTC, cztomczak requested changes
Thank you for your contribution @linesight. You can find my code comments attached to this review.

2025-02-07 20:50 UTC, cztomczak commented on unittests/main_test.py
> +            # cef.DpiAware.EnableHighDpiSupport()
`EnableHighDpiSupport` should be removed since it was removed upstream.

2025-02-07 20:50 UTC, cztomczak commented on unittests/main_test.py
> +        #                       cef.PyCookieManager)
If this was removed from upstream then remove it  here.

2025-02-07 20:50 UTC, cztomczak commented on unittests/main_test.py
> +        #                       cef.PyCookieManager)
If this was removed from upstream then remove it  here.

2025-02-07 20:50 UTC, cztomczak commented on unittests/osr_test.py
> +        # browser.SendFocusEvent(True)
Should call `SetFocus` here and remove `SendFocusEvent`.

2025-02-07 20:50 UTC, cztomczak commented on src/include/base/cef_ptr_util.h
> +#endif
Did you modify CEF header files?

2025-02-07 20:50 UTC, cztomczak commented on src/javascript_bindings.pyx
> +            if mainFrame.IsValid():
Should we print a log message when frame is invalid?

2025-02-07 20:54 UTC, cztomczak commented
Also @linesight , why does GitHub show me "This branch has conflicts that must be resolved" message?

2025-02-08 19:42 UTC, linesight commented on src/include/base/cef_ptr_util.h
> +#endif
yes, i even made a pull request at upstream cef 
https://github.com/chromiumembedded/cef/pull/3703
but upstream maintainer went for alternative direction

my current implementation  makes use of this header file at main_message_loop_external_pump_win.cpp
, so I decided to repair this header file

2025-02-08 19:58 UTC, cztomczak commented on src/include/base/cef_ptr_util.h
> +#endif
I suggest to copy code and put it outside of include/ dir.
In latest CEF I see the file was removed.

2025-02-10 05:58 UTC, linesight commented on tools/build.py
> +        os.environ["CEF_CCFLAGS"] = "-std=gnu++11 -DNDEBUG -Wall -Werror -Wno-deprecated-declarations"
It is inspired from upstream https://github.com/chromiumembedded/cef/blame/master/BUILD.gn#L2215

i was experimenting for linux build last year, so some of linux fix was getting into this pull request, although I didn't fully fix linux compilation

If you prefer not adding this half-done linux fix, I can take out this line of change

2025-02-10 06:25 UTC, linesight commented on tools/cython_setup.py
> +                r"C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10",
with `r` at the beginning of string, we shouldn't use double `\` 

If you prefer the style to be consistent, I can change line 151/152/154/158/159/160/162 to be single `\`
or you prefer those un-supported windows sdk to be removed from this python script, I can also proceed deleting those line 151/152/154/158/159/160/162, I don't have strong preference of either approach

2025-02-10 06:29 UTC, linesight commented on .gitignore
> +MediaDeviceSalts-journal
During my testing, those 2 files are created. For more info, check out https://github.com/chromiumembedded/cef/issues/3647
I think it is better to add these 2 files into .gitignore

2025-02-10 07:00 UTC, linesight commented on tools/automate.py
> +    args.append("--with-pgo-profiles")
see https://github.com/chromiumembedded/cef/issues/2956

2025-02-10 11:42 UTC, cztomczak commented on tools/build.py
> +        os.environ["CEF_CCFLAGS"] = "-std=gnu++11 -DNDEBUG -Wall -Werror -Wno-deprecated-declarations"
Let's keep it for Linux only then. Currently this flag applies to Mac as well. Let's also add a comment with a reason for that flag, similarly to CEF:  `# Don't warn about deprecated GDK/GTK functions.`.

2025-02-10 12:47 UTC, cztomczak commented on tools/automate.py
> +    args.append("--with-pgo-profiles")
I see.

CEF Automated Builds also use this flag in default builds, although not for all architectures: https://bitbucket.org/chromiumembedded/cef/wiki/AutomatedBuildSetup.md

2025-02-10 12:55 UTC, cztomczak commented on .gitignore
> +MediaDeviceSalts-journal
I assume it is created in current working directory, so location may vary.

2025-02-11 06:38 UTC, linesight commented on src/handlers/render_handler.pyx
> +            return True
I am not too proud of this few lines of code to fix pysdl2 use case, but I don't have a working alternative to fix pysdl2 example code. Can we leave the code as it is and add a TODO for future investigation?  ( coming up this hacky code took me most of time during this entire cefpython123 upgrade )

2025-02-11 07:26 UTC, linesight commented on src/include/cef_version.h
> +// Copyright (c) 2024 Marshall A. Greenblatt. All rights reserved.
`cef_version_info.h` was a recent new addition at upstream cef, didn't exist at upstream cef branch `6312`.  (my whole merge request was based on upstream cef branch `6312` )

2025-02-11 07:34 UTC, linesight commented on tools/build_distrib.py
> +        if python["version2"] in ((3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10)):
I missed updating this line to include python3.11, will fix shortly. For newer python version, I recalled I hit some serious issue for py3.12 last year, didn't have a quick fix, so I didn't actively pursue py3.12 release for this pull request. If newer    python (>=3.12) support is strongly desired, I would consider separate investigation, outside of this pull request

2025-02-11 12:20 UTC, cztomczak commented on src/handlers/render_handler.pyx
> +            return True
Do other off-screen rendering examples work fine with this change? 16 px default rect.

2025-02-11 16:25 UTC, linesight commented on src/handlers/render_handler.pyx
> +            return True
examplex\screenshot.py is able to produce screenshot png file of expected dimension. osr isn't super perfect, unittest fails with 
```
======================================================================
FAIL: test_osr (osr_test.OsrTest_IsolatedTest.test_osr)
Main entry point. All the code must run inside one
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\workspace\cefpython\unittests\osr_test.py", line 172, in test_osr
    check_auto_asserts(self, [] + client_handlers
  File "D:\workspace\cefpython\unittests\_common.py", line 88, in check_auto_asserts
    test_case.assertTrue(value, "Check assert: " +
AssertionError: False is not true : Check assert: AccessibilityHandler.loadComplete_True
```

I struggled several days to fix this unitest failure of osr, but couldn't find a way, then I gave up, instead focusing on functionality of the example py scripts

2025-02-11 16:36 UTC, cztomczak commented on src/handlers/render_handler.pyx
> +            return True
Looks like `loadComplete` event never occured. I would suggest to print all events and see what is going on. Upstream latest CEF refers to that event, so it should work: https://github.com/chromiumembedded/cef/blob/master/tests/ceftests/osr_accessibility_unittest.cc#L135

2025-02-11 16:37 UTC, cztomczak commented on src/handlers/render_handler.pyx
> +            return True
I recall you changed delay from 1500 ms to 800 ms somewhere, maybe it's not enough time to complete page loading?

2025-02-11 16:42 UTC, linesight commented on src/javascript_bindings.pyx
> +            if mainFrame.IsValid():
I don't have a strong preference log or not log when frame is invalid

2025-02-13 06:08 UTC, linesight commented on src/include/base/cef_ptr_util.h
> +#endif
I have updated `main_message_loop_external_pump_win.cpp` such that this `src/include/base/cef_ptr_util.h` is no longer referenced. For future update of cefpython, we can freely delete this `src/include/base/cef_ptr_util.h`
As this pull request is based on cef123, I prefer keeping the file in git depot. Whether to add/fix this `#endif` is not a big deal

2025-02-13 06:09 UTC, linesight commented on unittests/osr_test.py
> +        # browser.SendFocusEvent(True)
fixed

2025-02-13 06:09 UTC, linesight commented on tools/build.py
> +        os.environ["CEF_CCFLAGS"] = "-std=gnu++11 -DNDEBUG -Wall -Werror -Wno-deprecated-declarations"
fixed

2025-02-13 11:57 UTC, cztomczak commented on examples/snippets/network_cookies.py
> -"""
CanGetCookie/CanSetCookie were moved to `cef_resource_request_handler.h` and are now named `CanSendCookie` / `CanSaveCookie` in `CefCookieAccessFilter`. We should expose that API and restore the example.

2025-02-13 12:04 UTC, cztomczak commented on api/ApplicationSettings.md
> -### accept_language_list
When API changes we should update the Migration Guide document:
https://github.com/cztomczak/cefpython/blob/master/docs/Migration-guide.md

2025-02-15 04:04 UTC, linesight commented on src/compile_time_constants.pxi
> -
fixed

2025-02-15 04:04 UTC, linesight commented on tools/common.py
>          contents = fp.read()  # no need to decode() as "rU" specified
fixed

2025-02-15 04:06 UTC, linesight commented on .gitignore
> +MediaDeviceSalts-journal
abolute location of such files could vary, but .gitignore would recursively match the files, so this proposed change should be fine

2025-02-15 04:06 UTC, linesight commented on examples/screenshot.py
> +    # browser.SendFocus(True)
fixed

2025-02-15 04:08 UTC, linesight commented on src/cookie.pyx
> +        # return CefBasetimeTToDatetime(self.cefCookie.creation)
it has been revisited and fixed

2025-02-15 04:09 UTC, linesight commented on src/cookie.pyx
> +        pass
it has been revisited and fixed

2025-02-15 04:09 UTC, linesight commented on src/cookie.pyx
> +        pass
it has been revisited and fixed

2025-02-15 04:10 UTC, linesight commented on src/cookie.pyx
> +        pass
it has been revisited and fixed

2025-02-15 04:10 UTC, linesight commented on src/cookie.pyx
> +        pass
it has been revisited and fixed

2025-02-15 04:12 UTC, linesight commented on unittests/main_test.py
> +        #                       cef.PyCookieManager)
fixed

2025-02-15 04:12 UTC, linesight commented on unittests/main_test.py
> +        #                       cef.PyCookieManager)
fixed

2025-02-15 04:14 UTC, linesight commented on tools/cython_setup.py
> +                r"C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10",
older lines of windows sdk path have been removed

2025-02-15 04:16 UTC, linesight commented on src/browser.pyx
> +    #                 "messageName=%s" % messageName)
fixed

2025-02-15 04:17 UTC, linesight commented on src/client_handler/request_context_handler.h
> +    // virtual CefRefPtr<CefCookieManager> GetCookieManager() override;
fixed

2025-02-15 04:18 UTC, linesight commented on src/client_handler/request_context_handler.cpp
> +// }
whole `src/client_handler/request_context_handler.cpp` is removed

2025-02-15 04:20 UTC, linesight commented on src/cookie.pyx
> +    #             <CefRefPtr[CefCompletionCallback]?>nullptr)
fixed

2025-02-15 04:20 UTC, linesight commented on src/cookie.pyx
> +    #     return None
fixed

2025-02-15 04:21 UTC, linesight commented on src/extern/cef/cef_browser.pxd
> +        # void SendFocusEvent(cpp_bool setFocus)
fixed

2025-02-15 04:21 UTC, linesight commented on src/frame.pyx
> +    #     self.GetCefFrame().get().LoadString(cefValue, cefUrl)
fixed

2025-02-15 04:22 UTC, linesight commented on src/include/capi/cef_accessibility_handler_capi.h
> +// Copyright (c) 2024 Marshall A. Greenblatt. All rights reserved.
fixed

2025-02-15 04:23 UTC, linesight commented on src/include/internal/cef_linux.h
> -// Copyright (c) 2010 Marshall A. Greenblatt. All rights reserved.
fixed

2025-02-15 04:23 UTC, linesight commented on src/include/internal/cef_mac.h
> -// Copyright (c) 2010 Marshall A. Greenblatt. All rights reserved.
fixed

2025-02-15 04:23 UTC, linesight commented on src/include/test/cef_test_helpers.h
>  #include "include/cef_frame.h"
fixed

2025-02-15 04:23 UTC, linesight commented on src/settings.pyx
> +        #     del cefString
fixed

2025-02-15 04:24 UTC, linesight commented on src/settings.pyx
> +        #     del cefString
fixed

2025-02-15 04:24 UTC, linesight commented on src/settings.pyx
> +        #     cefAppSettings.ignore_certificate_errors = int(appSettings[key])
fixed

2025-02-15 04:25 UTC, linesight commented on src/settings.pyx
> +        #     del cefString
fixed

2025-02-15 04:26 UTC, linesight commented on src/time_utils.pyx
> +
this `src/time_utils.pyx` is revisited, no more proposed change to this file

2025-02-15 04:27 UTC, linesight commented on src/utils.pyx
> +# TID_FILE = cef_types.TID_FILE
fixed

2025-02-15 04:27 UTC, linesight commented on src/utils.pyx
> +    # TID_FILE,
fixed

2025-02-15 04:28 UTC, linesight commented on unittests/main_test.py
> +            # cef.DpiAware.EnableHighDpiSupport()
fixed

2025-02-15 04:32 UTC, linesight commented on examples/pysdl2.py
> +    # browser.SendFocus(True)
fixed

2025-02-15 04:32 UTC, linesight commented on src/client_handler/request_handler.cpp
> +// }
fixed

2025-02-15 04:33 UTC, linesight commented on src/client_handler/resource_handler.h
> +  // virtual bool CanGetCookie(const CefCookie& cookie) ;
fixed

2025-02-15 04:33 UTC, linesight commented on src/client_handler/resource_handler.h
> +  // virtual bool CanSetCookie(const CefCookie& cookie) ;
fixed

2025-02-15 04:34 UTC, linesight commented on src/frame.pyx
> +        if self.cefFrame.get():
fixed

2025-02-15 04:35 UTC, linesight commented on src/handlers/request_handler.pyx
> +#         sys.excepthook(exc_type, exc_value, exc_trace)
fixed

2025-02-15 04:48 UTC, linesight commented on src/client_handler/resource_handler.cpp
> +// }
fixed

2025-02-15 04:48 UTC, linesight commented on api/LifespanHandler.md
>  There will be no "window.opener" property available in the popup window.
fixed

2025-02-15 04:48 UTC, linesight commented on src/settings.pyx
> +        #             int(appSettings[key])
fixed

2025-02-15 04:48 UTC, linesight commented on src/settings.pyx
> +        #         cefBrowserSettings.web_security = cef_types.STATE_ENABLED
fixed

2025-02-15 04:50 UTC, linesight commented on src/time_utils.pyx
> +#     return CefTimeTToDatetime(cefTime)
this block of code is restored. No more propose change to this file

2025-02-15 04:53 UTC, linesight commented on tools/cython_setup.py
> +            "language_level": "2",
i have restored the line and keep this `language_level` as `2`
So no proposed change to this block of code

2025-02-15 04:54 UTC, linesight commented on src/settings.pyx
> +        #                 cef_types.STATE_ENABLED)
fixed

2025-02-15 04:55 UTC, linesight commented on src/client_handler/resource_handler.cpp
> +// }
fixed

2025-02-15 04:56 UTC, linesight commented on src/dpi_aware_win.pyx
> +        #CefEnableHighDPISupport()
fixed

2025-02-15 05:51 UTC, linesight commented on src/settings.pyx
> +        #     del cefString
fixed

2025-02-15 07:13 UTC, linesight commented on src/handlers/render_handler.pyx
> +            return True
I have updated `unittests\osr_test.py` 's `_OnAccessibilityTreeChange`

2025-02-15 19:35 UTC, linesight commented on examples/snippets/network_cookies.py
> -"""
`http://www.html-kit.com/tools/cookietester/`  website is now dead, do you have any suggestion what alternative website is?

2025-02-16 08:08 UTC, linesight commented on examples/snippets/network_cookies.py
> -"""
I have added preliminary code support for `CanSendCookie` and `CanSaveCookie`, this example script has been restored and slightly updated

2025-02-16 08:28 UTC, linesight commented on src/extern/cef/cef_app.pxd
> -    cdef void CefEnableHighDPISupport() nogil
This is a good callout, but unfortunately I don't have much experience for the manifest file for a windows scripted (not packaged) application.

2025-02-16 08:43 UTC, linesight commented
I think I have addressed most (if not all ) techinical feedback from @cztomczak , really appreciate you also double check at upstream cef
Some feedback such as exposing new cef's API is nice to do, but to me, it seems to fall out of the my original scope of this pull request, I would like to consider a separate task for such enhancement. 
If this technical pull request is accepted, I would make a follow-up/new pull request for the migration guide update (sorry, updating doc is too time consuming and a bit distracting while fixing technical issue, I would rather a seperate effort for doc)

2025-02-17 17:46 UTC, cztomczak commented on src/include/cef_application_mac.h
> -// Copyright (c) 2011 Marshall A. Greenblatt. All rights reserved.
This file should not be removed, but should be updated.

It seems you have still not synced include/ directory with CEF git branch 6312.

2025-02-17 17:47 UTC, cztomczak commented on src/include/internal/cef_types_mac.h
> -// Copyright (c) 2014 Marshall A. Greenblatt. All rights reserved.
This file should not be removed, but should be updated.

2025-02-17 17:47 UTC, cztomczak commented on src/include/internal/cef_types_linux.h
This file should not be removed, but should be updated.

2025-02-17 17:51 UTC, cztomczak commented on examples/snippets/network_cookies.py
> -"""
I would google "cookie test" and choose any website that works.

2025-02-17 17:52 UTC, cztomczak commented on examples/snippets/network_cookies.py
> -"""
In regards to changing html-kit cookietester we used.

2025-02-17 18:01 UTC, cztomczak commented on src/browser.pyx
> -    cpdef py_void SendFocusEvent(self, py_bool setFocus):
For backwards compatibility we could keep this method and just call `SetFocus`. Easy fix and many apps wouldn't break.

2025-02-17 18:06 UTC, cztomczak commented on src/extern/cef/cef_browser.pxd
> +        # cpp_bool SendProcessMessage(CefProcessId target_process,
We can remove this commented out code.

2025-02-17 18:11 UTC, cztomczak commented on src/frame.pyx
> +cdef str GetUniqueFrameId(int browserId, py_string frameId):
I guess previously it used object because of py2 <> py3 string differences.  Hmm now we use Py2 in cython and Py3 for apps and this works fine?

2025-02-17 18:25 UTC, cztomczak commented on tools/build_distrib.py
> +SUPPORTED_PYTHON_VERSIONS = [(2, 7), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (3, 11)]
We should drop support  Python 2.7. Also old Python 3 version such as 3.4, 3.5, 3.6.... we don't need that. We should only support latest popular Py 3 versions.

2025-02-17 18:27 UTC, cztomczak commented on tools/build_distrib.py
> +SUPPORTED_PYTHON_VERSIONS = [(2, 7), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (3, 11)]
Just for information. This PR is about CEF upgrade. Support in regards to Python versions should be done separately.

2025-02-17 18:33 UTC, cztomczak commented
@linesight Thank you for your work on this PR. I added a few comments, we're almost good to merge. I can accept a separate PR for documentation changes.

Are all supported examples working fine?
My Windows machine is currently broken, can't test.

2025-02-17 19:20 UTC, linesight commented on tools/build_distrib.py
> +SUPPORTED_PYTHON_VERSIONS = [(2, 7), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (3, 11)]
Thanks for the info.

2025-02-17 19:27 UTC, linesight commented on src/include/cef_application_mac.h
> -// Copyright (c) 2011 Marshall A. Greenblatt. All rights reserved.
fixed

2025-02-17 19:27 UTC, linesight commented on src/include/internal/cef_types_linux.h
fixed

2025-02-17 19:31 UTC, linesight commented on src/include/internal/cef_types_mac.h
> -// Copyright (c) 2014 Marshall A. Greenblatt. All rights reserved.
fixed

2025-02-17 19:34 UTC, linesight commented on src/extern/cef/cef_browser.pxd
> +        # cpp_bool SendProcessMessage(CefProcessId target_process,
fixed

2025-02-17 20:20 UTC, linesight commented on src/frame.pyx
> +cdef str GetUniqueFrameId(int browserId, py_string frameId):
`frameId` is now of `py_string` , to align with how current upstream cef123 is treating frame id as a string, see
https://github.com/chromiumembedded/cef/commit/2f1e782f62c21dbc2e35d546aed7a0d69bdd97c4
I don't have histocial knowledge why `object` type was used, but I guess it was due to old frame id being `int64_t` type, didn't have nice or convenient mapping in cython

as `frameId` is now of string type, it is natural to change to function `GetUniqueFrameId` return type to string as well. More specifc type is, in general, more preferred than general type `object`.

For "Py2 in cython" comment, I think you are referring to 
```
"language_level": 2,
```
still being used in `cython_setup.py`

I noticed this line at the beginning of development of this pull request, I tried to get rid of this line at first, then I met warning
```
cythoning cefpython_py311.pyx to cefpython_py311.cpp
D:\workspace\cefpython\venv311\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: D:\workspace\cefpython\build\build_cefpython\cefpython_py311.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
```

I didn't mean to introduce extra warning, then I put this `language_level` line back. How cython deals with this `language_level` internally isn't my primrary concern. Suppose you use python3 to execute this build instruction and example code, things work fine

2025-02-17 21:22 UTC, cztomczak commented on src/frame.pyx
> +cdef str GetUniqueFrameId(int browserId, py_string frameId):
`language_level` can be set to `2` or `3` or even `3str`. Changing it would require extensive testing of all APIs to make sure nothing got broken.

> language_level (2/3/3str), default=None
> Globally set the Python language level to be used for module compilation. Default is None, indicating compatibility with Python 3 in Cython 3.x and with Python 2 in Cython 0.x. To enable Python 3 source code semantics, set this to 3 (or 3str) at the start of a module or pass the “-3” or “–3str” command line options to the compiler. For Python 2 semantics, use 2 and “-2” accordingly. Before Cython 3.1, the 3str option enabled Python 3 semantics but did not change the str type and unprefixed string literals to unicode when the compiled code runs in Python 2.x. In Cython 3.1, 3str is an alias for 3. Language level 2 ignores x: int type annotations due to the int/long ambiguity. Note that cimported files inherit this setting from the module being compiled, unless they explicitly set their own language level. Included source files always inherit this setting.

Ref:
- https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives
- https://stackoverflow.com/a/53992016/623622

2025-02-17 21:25 UTC, cztomczak commented on src/frame.pyx
> +cdef str GetUniqueFrameId(int browserId, py_string frameId):
In requirements.txt Cython version is `Cython == 0.29.36`. That version supports only language level 2 (Python 2).
I just checked and see latest version is Cython `3.0.12` which supports `3` and `3str`:
https://github.com/cython/cython/releases

2025-02-17 21:30 UTC, cztomczak commented on src/frame.pyx
> +cdef str GetUniqueFrameId(int browserId, py_string frameId):
In Cython i recall much confusion with str/unicode types. When you define function returning `str` type it really is Python 2 byte string from what I recall. To return unicode string I think that;s the reason for `object` type - when project had to support both Python 2 and Python 3. I'm not sure now, but it was all confusing.

2025-02-17 21:44 UTC, cztomczak commented on src/frame.pyx
> +cdef str GetUniqueFrameId(int browserId, py_string frameId):
More on Cython strings: https://cython.readthedocs.io/en/stable/src/tutorial/strings.html
> Cython supports four Python string types: bytes, str, unicode and basestring...

A nice read 😊

2025-02-17 21:48 UTC, cztomczak commented on src/frame.pyx
> +cdef str GetUniqueFrameId(int browserId, py_string frameId):
Changing cython language level might change how strings are handled, or other things I don't know. I dont recommend changing it without re-testing of all APIs. Our unit tests are limited.

2025-02-17 21:52 UTC, linesight commented on src/browser.pyx
> -    cpdef py_void SendFocusEvent(self, py_bool setFocus):
fixed

2025-02-17 22:08 UTC, linesight commented
> @linesight Thank you for your work on this PR. I added a few comments, we're almost good to merge. I can accept a separate PR for documentation changes.
> 
> Are all supported examples working fine? My Windows machine is currently broken, can't test.

I have checked all example python scripts, including those snippets, they are good to run, with below limitation - 

- with updated network_cookies.py and other work around cookie in this pull request, `CanSendCookie` and `CanSaveCookie` is not fired in the python handler code. I haven't been able to  figure out why, there is a open thread at https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=19063&p=52085&hilit=CanSendCookie#p52085

- gtk2.py , gtk3.py -  I hit gtk related package dependency installation problem, 

```
(venv311) D:\workspace\cefpython\build>pip install pyGObject
Collecting pyGObject
  Downloading pygobject-3.50.0.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 6.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      + meson setup C:\Users\opopp\AppData\Local\Temp\pip-install-3u6vlyb1\pygobject_5717a74cecbb4a6ab467f21fd17595fa C:\Users\opopp\AppData\Local\Temp\pip-install-3u6vlyb1\pygobject_5717a74cecbb4a6ab467f21fd17595fa\.mesonpy-4asek4sk -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md -Dtests=false -Dwheel=true --wrap-mode=nofallback --native-file=C:\Users\opopp\AppData\Local\Temp\pip-install-3u6vlyb1\pygobject_5717a74cecbb4a6ab467f21fd17595fa\.mesonpy-4asek4sk\meson-python-native-file.ini
      The Meson build system
      Version: 1.7.0
      Source dir: C:\Users\opopp\AppData\Local\Temp\pip-install-3u6vlyb1\pygobject_5717a74cecbb4a6ab467f21fd17595fa
      Build dir: C:\Users\opopp\AppData\Local\Temp\pip-install-3u6vlyb1\pygobject_5717a74cecbb4a6ab467f21fd17595fa\.mesonpy-4asek4sk
      Build type: native build
      Project name: pygobject
      Project version: 3.50.0
      C compiler for the host machine: cl (msvc 19.41.34123 "Microsoft (R) C/C++ Optimizing Compiler Version 19.41.34123 for x64")
      C linker for the host machine: link link 14.41.34123.0
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Program python3 found: YES (D:\workspace\cefpython\venv311\Scripts\python.exe)
      Run-time dependency python found: YES 3.11
      Found pkg-config: YES (C:\msys64\ucrt64\bin\pkg-config.EXE) 2.2.0
      Found CMake: C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.EXE (3.29.5)
      Run-time dependency gobject-introspection-1.0 found: NO (tried pkgconfig and cmake)
      Not looking for a fallback subproject for the dependency gobject-introspection-1.0 because:
      Use of fallback dependencies is disabled.

      ..\meson.build:31:9: ERROR: Dependency 'gobject-introspection-1.0' is required but not found.

      A full log can be found at C:\Users\opopp\AppData\Local\Temp\pip-install-3u6vlyb1\pygobject_5717a74cecbb4a6ab467f21fd17595fa\.mesonpy-4asek4sk\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
so I am not able to confidently say they are good. Given my intent is windows focus, gtk isn't a popular GUI framework at windows, I would like to defer gtk investigation until cefpython-on-linux starts

2025-02-17 22:20 UTC, cztomczak commented on src/frame.pyx
> +cdef str GetUniqueFrameId(int browserId, py_string frameId):
It's a cdef, so internal function. It doesn't much matter here. What matters is what you expose to Python API - a byte string or unicode string - we should be consistent with the rest of the API.

2025-02-17 22:28 UTC, cztomczak commented
That's okay. As I understand this PR is for Windows support.
Regarding cookies - please create an issue in the tracker with a label v123 or somerthing.
I will merge this.
Thank you!

2025-02-17 22:34 UTC, merged

2025-02-17 22:43 UTC, cztomczak commented
We should also updated Build Instructions: https://github.com/cztomczak/cefpython/blob/master/docs/Build-instructions.md

2025-02-18 13:19 UTC, cztomczak commented
This PR was reverted. Please send changes to `cefpython123` branch,.

2025-02-18 13:45 UTC, cztomczak commented
@linesight Also please squash your commits into one big commit with a title like "Update CEF to version 123.0.7 with Chromium-123.0.6312.46 (Windows tested)". If you don't squash, I can squash it and merge, but then I don't know how you will be credited in the GitHub Contributors view (Insights tab).

2025-02-18 15:41 UTC, cztomczak commented
Also documentation should be in one PR or another PR, but let's not mix in both PRs.

I can merge when I have an opportunity to test on a Windows machine.

2025-02-18 17:59 UTC, linesight commented
As there has been multiple dicussions and multiple git commits at my branch to address each feedback, it is way too much effort to squash my commit at my branch on my side. I want my branch to preserve my original git commit history. It is better you squash it during merge. Or you can configure the pull request setting at your depot to allow squash merging.  
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests